vaadin/vaadin-context-menu

demo/index.html
This PR fixes the syntax highlighting on the basic example page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/10)
=> Wrap the basic example in an element to fix syntax highlighting

bower.json, demo/index.html, test/index.html, test/selection.html, test/touch.html, vaadin-context-menu-overlay.html, vaadin-context-menu.html, vaadin-long-touch.html
Fixes vaadin/components-team-tasks#200
Scrolling is still enabled when overlay is opened, decided to leave it
like that for nowScrolling is still enabled when overlay is opened,
decided to leave it like that for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/12)
=> Add touch support

vaadin-contextmenu-event.html
Fixes #32 
IOS (for some reason not IOS simulator though) updates clientX/clientY values of the cached sourceEvent touch on touchmove (the touch instance is probably shared between different events). This will result in the touchJob never getting stopped.
The PR addresses the issue by caching the original X and Y coordinates on touchstart and compare to those values later on.
The PR doesn't include tests since the original issue doesn't occur on IOS simulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/35)
=> Cache original touchstart coordinates on touch start

.travis.yml
Stop build if one of tasks (e.g. linter) is failing. No need to wait for other tasks. Report errors ASAP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/48)
=> Stop Travis build if task is failing

.travis.yml, README.md, demo/advanced.html, demo/index.html, index.html, test/index.html, test/integration.html
Connected to #42 
Also:
- Removed `set -e` from Travis build as it prevents `travis_retry` from repeating tasks
- Use `webcomponents-lite.min.js` instead of `webcomponents-lite.js` for demos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/56)
=> Add test for .open(e) method

test/integration.html, vaadin-context-menu-overlay.html, vaadin-context-menu.html
Fixes #30 
I made another component for this fix: https://github.com/vaadin/vaadin-overlay/pull/1
Please review the PR above before this one. In case that we are fine with `vaadin-overlay` I'll bump its version and change it in `bower.json` of this PR. Currently, it is pointing to the `init` branch, which is a temporary solution for being able to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/62)
=> Make context-menu 'modal' by adding vaadin-overlay

test/overlay.html, vaadin-context-menu.html
Fixes #65 
With this change context-menu will behave in Linux-way: the second right-click will close the context menu triggered by the first right-click.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/66)
=> Prevent contextmenu on backdrop

vaadin-contextmenu-event.html
Separated the `touchend` actions to a dedicated function. We previously assumed that `tap` occurs always on `touchend` but that's clearly not the case.
Fixes #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/73)
=> Make sure active touch job is stopped on touchend

test/touch.html, vaadin-contextmenu-event.html
Regression after iron-overlay-behavior version 1.10.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/75)
=> Fix iOS closing the overlay in first touch.

test/touch.html, vaadin-contextmenu-event.html
Connects to #78
The issue still occurs on Android devices. Fix by preventing the 'tap' gesture on native 'contextmenu' event also (used in Anrdoid implementation of the gesture)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/81)
=> Prevent tap from closing the overlay on Android device

demo/context-menu-basic-demos.html
Connects to https://github.com/vaadin/components-team-tasks/issues/280
Add demo ready listeners to fix query selectors in `Custom Listener` and `JavaScript API` examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/102)
=> Fix custom listeners

bower.json
Fixes #114 
Dependency not used since https://github.com/vaadin/vaadin-context-menu/commit/4f8798998c4ad4aacb4b3675dd596225e815bfa7#diff-66a399af7bafbcfacad65a17d9eb94c8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/118)
=> Remove iron-overlay-behavior

bower.json, demo/context-menu-advanced-demos.html, demo/context-menu-basic-demos.html, demo/index.html, test/context.html, test/selection.html
We no longer need these after having #125 merged.
Also replaced native `button` with `vaadin-button` in demos for better appearance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/127)
=> Remove Paper dependencies

theme/lumo/vaadin-context-menu.html
The ShadyCSS workaround in vaadin-list-box theme causes the checkmark to be visible inside context menu in Chrome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/137)
=> Hide selected item checkmark

test/context.html, test/integration.html, test/not-animated-styles.html, test/overlay.html, test/properties.html, test/selection.html, test/touch.html
In the upcoming `vaadin-overlay` release, the animations feature is to be introduced, which in conjunction with the default animation styles in latest Lumo (`lumo-menu-overlay-core`) cause random failures.
Related https://github.com/vaadin/vaadin-combo-box/pull/632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/146)
=> Disable animations in tests

.travis.yml, analysis.json, bower.json, demo/context-menu-basic-demos.html, src/vaadin-context-menu.html, test/renderer.html, test/test-suites.js
Fixes #169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/171)
=> Add renderer support

bower.json, src/vaadin-context-menu.html, test/renderer.html
Connected to https://github.com/vaadin/components-team-tasks/issues/409
The behaviour of the renderer in this case is slightly different from other overlay dependent components as `renderer` can be invoked only once `context` is available. It is assigned on `open`, so there is no way to manually invoke `render` before `context-menu` is opened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/186)
=> Manual rendering of the content

demo/context-menu-basic-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/195)
=> Fix context menu basic example to mention renderer [skip ci]

theme/material/vaadin-context-menu-styles.html
The `vaadin-context-menu` does not install neither `vaadin-list-box` nor `vaadin-item` dependencies, and the users could technically use `paper-listbox` instead, although we do not promote that in demos anymore. In that case, these imports could cause 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/198)
=> Remove list-box and item imports from Material theme

src/vaadin-contextmenu-items-mixin.html, test/items.html
Currently, the (sub) menus don't close on backdrop click (mobile). This PR fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/202)
=> Enable menu close on backdrop click

bower.json, src/vaadin-contextmenu-items-mixin.html, test/items.html
Connected to #214 
This is a fix for the "Nested Menu Items" demo. The basic context-menu will be fixed in overlay PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/215)
=> fix: workaround document click event in Firefox

src/vaadin-contextmenu-event.html, test/touch.html
Fixes #219 
Tests are now covering the major part of the code.
Some `Polymer.Gestures` specific code is not covered (due to the ticket specification) such as `name`, `flow`, `reset` function which is used internally in `gesture` util.
As for the removing `this._cancelTimer();` from `touchstart` it will be removed on `touchend`, so it's not required over there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/221)
=> Improve test coverage for vaadin-contextmenu gesture event

theme/lumo/vaadin-context-menu-styles.html
Fixes #222 
Looks like the `:host(.vaadin-menu-list-box) ` does not affect CSS selector specificity in Safari:
Fixed by moving the corresponding style block below. Could be related to class selectors only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/224)
=> fix: ensure list-box items CSS specificity in Safari

.eslintrc.json, src/vaadin-context-menu-overlay.html, src/vaadin-context-menu.html, test/items.html
Related to vaadin/vaadin-menu-bar#17
Similar to #223 but now for right-aligned menu, so implementation is different.
Submenu overlay is left-aligned:
Submenu overlay is also right aligned and takes parent's content width into account:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/228)
=> fix: ensure consistent right alignment for nested menus

src/vaadin-contextmenu-items-mixin.html
Connected to vaadin/vaadin-menu-bar#73
This is an improvement unlocking the possibility to extend `vaadin-context-menu` in the menu-bar.
One of the use cases for that is a global "contextmenu" listener which is hard to remove otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/245)
=> fix: support extending by not hardcoding tag name

src/vaadin-context-menu-overlay.html, src/vaadin-context-menu.html, src/vaadin-contextmenu-items-mixin.html, test/items.html
Propagate theme attribute to nested overlays, list-boxes and items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/238)
=> Propagate theme attribute

src/vaadin-contextmenu-items-mixin.html, test/items.html, theme/lumo/vaadin-context-menu-styles.html
Fixes https://github.com/vaadin/vaadin-context-menu/issues/246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/248)
=> Switch touchstart to always use mouseover

theme/lumo/vaadin-context-menu-styles.html
Fixes #247
Cannot come up with a proper test for it.
`max-height` is already defined in [`vaadin-lumo-styles`](https://github.com/vaadin/vaadin-lumo-styles/blob/master/mixins/menu-overlay.html#L57-L73) and `content` part is inheriting the `max-height`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/249)
=> Remove max-height from content as it's present in lumo-styles

src/vaadin-contextmenu-items-mixin.html
Only the context-menu items should be highlighted on hover.
=> fix: prevent adding styles to arbitrary component in overlay

src/vaadin-context-menu.html, test/context.html, test/items.html
Before this change the overlay was left open after detaching the context-menu
Fixes vaadin/vaadin-menu-bar-flow#62
=> Close context-menu on disconnect

magi-p3-post.json, test/selection.html
The version was pinned by ea64f2a4cb342945d254ebc9beb465e9444e6a0a, let's see if we still need it.
=> chore: unpin webcomponents polyfills

src/interfaces.d.ts, src/vaadin-context-menu.d.ts, src/vaadin-context-menu.js
1. Added `@fires` annotations to enable VS Code lit-plugin code completion support.
2. Aligned `item-selected` event description.
=> chore: add JSDoc for custom events [skip ci]

src/interfaces.d.ts
Add a type definition for the `details` object inside of the `ContextMenuRendererContext` interface.
Fix vaadin/vaadin-context-menu#309
=> fix: define details type at ContextMenuRendererContext

src/vaadin-contextmenu-items-mixin.html, test/items.html
Cherry-pick of https://github.com/vaadin/web-components/pull/7203
Fixes https://github.com/vaadin/web-components/issues/7202 for Vaadin 14.
- Bugfix
=> fix: reset tabindex to -1 when initializing menu item
