bower.json
index.html
vaadin-context-menu-overlay.html
vaadin-context-menu.html

Fixes #4 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/6)

Added API docs

---

demo/advanced.html
docs/vaadin-context-menu-overview.adoc
test/overlay.html
vaadin-context-menu.html

Fixes #7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/9)

Replace no-close with close-on

---

bower.json
demo/advanced.html
demo/index.html
vaadin-context-menu.html

Fixes #2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/8)

Style mixins

---

demo/advanced.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/14)

Apply minor cleanup and fix for IE to the advanced demo

---

demo/advanced.html

Fixes #15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/20)

Fix example in IE11. Fixes: #15

---

demo/index.html
docs/vaadin-context-menu.adoc
test/context.html
test/overlay.html
test/properties.html
test/selection.html
test/template.html
test/touch.html
vaadin-context-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/17)

Accept a context in the open method.

---

demo/index.html
test/device-detector.html
test/index.html
test/touch.html
vaadin-context-menu-overlay.html
vaadin-device-detector.html

Fixes #13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/22)

Detect phones based on touch support and device width

---

test/overlay.html
test/touch.html
vaadin-context-menu.html
vaadin-long-touch.html

Fixes #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/27)

Pass touchstart as sourceEvent for long touch

---

test/context.html
test/properties.html
test/template.html
test/touch.html
vaadin-context-menu.html
vaadin-contextmenu-event.html

...into vaadin-contextmenu event
Fixes #26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/31)

Combined default vaadin-long-touch and contextmenu events 

---

README.md
bower.json
docs/vaadin-context-menu.adoc
vaadin-context-menu-overlay.html
vaadin-context-menu.html
vaadin-contextmenu-event.html
vaadin-device-detector.html

Fixes #29 
PR to add docs to vaadin.com/docs/ here: https://github.com/vaadin/vaadin-docs/pull/64
Preview for webcomponents.org demo: https://beta.webcomponents.org/preview/vaadin/vaadin-context-menu/0f9e6f84dbf17390c33500d8495de1c78fd3a034/demo/demo/index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/34)

Revise docs

---

demo/index.html
test/template.html
test/touch.html
vaadin-context-menu-overlay.html
vaadin-context-menu.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/37)

Fix position of overlay in mobile, and scroll for long content, fixes #33

---

test/context.html
test/overlay.html
test/properties.html
test/selection.html
test/template.html
test/touch.html
vaadin-context-menu.html

Connected to #46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/50)

Make `opened` public and read-only

---

test/overlay.html
vaadin-contextmenu-event.html

Fixes #47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/57)

Support accessing native context menu by holding shift key on opening

---

test/context.html
vaadin-context-menu.html

Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/60)

Close previous context menu before opening the next one

---

test/integration.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/63)

Fix test and bump iphone ipad version

---

bower.json
demo/advanced.html

Fixes #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/74)

Use vaadin-grid 2 in the integration demo

---

test/touch.html
vaadin-contextmenu-event.html

Fixes #78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/79)

Prevent touchend in capture mode

---

.eslintrc.json
.gitignore
.travis.yml
bower.json
demo/advanced.html
demo/common.html
demo/index.html
documentation.json
gulpfile.js
index.html
package.json
test/.eslintrc.json
test/common.js
test/context.html
test/device-detector.html
test/index.html
test/integration.html
test/overlay.html
test/properties.html
test/selection.html
test/template.html
test/touch.html
vaadin-context-menu-overlay.html
vaadin-context-menu.html
vaadin-contextmenu-event.html
vaadin-device-detector.html
wct.conf.js

Connects to #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/82)

Convert to pure Polymer2 ES6

---

demo/advanced.html
documentation.json
package.json
vaadin-context-menu.html

Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/84)

Remove mixins

---

analysis.json
vaadin-context-menu.html

Fixes #89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/91)

Add @mixes Polymer.GestureEventListeners annotation

---

test/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/92)

Disabling shadydom tests in chrome

---

bower.json
demo/index.html
vaadin-context-menu.html

Changing first basic demo text, removing comment for property-effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/93)

Intuitive demo text

---

vaadin-context-menu.html

Simplifies template fetching by using querySelector.

Simplify template fetching

---

package-lock.json
test/touch.html
vaadin-contextmenu-event.html

Connected to #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/98)

Fix iOS closing the overlay 

---

test/touch.html
vaadin-context-menu.html

Fixes #97
Depends on vaadin/vaadin-overlay#25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/99)

Add constrained overlay alignment / sizing support

---

analysis.json
vaadin-context-menu.html
vaadin-device-detector.html

Fixes #108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/109)

Cleanup and styling documentation

---

demo/context-menu-advanced-demos.html
demo/context-menu-basic-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/120)

Convert demos to ES5

---

analysis.json
bower.json
demo/context-menu-basic-demos.html
demo/index.html
test/overlay.html
vaadin-context-menu.html

Fixes #119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/121)

Use default white background for context menu

---

bower.json
demo/context-menu-basic-demos.html
demo/context-menu-integration-demos.html
demo/demos.json
demo/index.html

vaadin-list-box and vaadin-item should be the normal way to create context menus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/122)

Use vaadin-list-box in demos as default

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/123)

Fix screenshot path

---

README.md

Fixes #128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/129)

Fix inline demo polyfill path

---

src/vaadin-context-menu.html
test/overlay.html

Fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/130)

Fix: close context menu on outside contextmenu event

---

src/vaadin-context-menu.html
test/overlay.html

Fixes #131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/132)

Support --vaadin-overlay-viewport-bottom CSS property

---

src/vaadin-context-menu.html
theme/lumo/vaadin-context-menu.html

Fixes #133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/134)

Move small viewport behavior styles from core to Lumo

---

src/vaadin-context-menu.html
test/selection.html

Fixes #135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/136)

Replace child focus with timeOut.run

---

bower.json
demo/context-menu-advanced-demos.html
src/vaadin-context-menu.html
test/context.html
test/selection.html
test/template.html

Fixes #149 
Connected to https://github.com/vaadin/vaadin-overlay/pull/76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/150)

Upgrade to vaadin-overlay ^3.0.0

---

demo/context-menu-advanced-demos.html
demo/context-menu-basic-demos.html
demo/demos.json

Connected to https://github.com/vaadin/components-team-tasks/issues/347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/151)

Update the styling example

---

theme/lumo/vaadin-context-menu.html

Fixes vaadin/vaadin-context-menu#152
Depends on vaadin/vaadin-list-box/pull/27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/154)

Fix selected item styles after switching to overlay v3 #150

---

.travis.yml
test/context.html
test/device-detector.html
test/external-imports.html
test/integration.html
test/overlay.html
test/properties.html
test/selection.html
test/template.html
test/touch.html
wct.conf.js

Connected to vaadin/components-team-tasks#332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/155)

Use bare module specifiers in the P3 conversion

---

test/integration.html
test/touch.html

Connected to vaadin/components-team-tasks#390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/173)

Fix tests for IE11 and Polymer 3 with new modulizer

---

analysis.json
src/vaadin-context-menu.html
test/renderer.html

Please `bower link vaadin-overlay` from `throw-error` branch before testing.
Requires https://github.com/vaadin/vaadin-overlay/pull/104
Connected to https://github.com/vaadin/components-team-tasks/issues/391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/174)

Throw error when template and renderer are used simultaneously

---

bower.json
demo/context-menu-basic-demos.html
demo/context-menu-grid-demos.html
demo/context-menu-styling-demos.html

Fixes #175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/176)

Update demos to prefer renderers

---

demo/context-menu-basic-demos.html
demo/context-menu-grid-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/178)

small changes to demos

---

demo/context-menu-basic-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/180)

Replace `new` with `createElement` in demos to avoid errors in P3

---

src/vaadin-context-menu.html

Fixes #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/183)

Reuse dom in the docs example

---

demo/context-menu-basic-demos.html
demo/context-menu-grid-demos.html

Connects to https://github.com/vaadin/components-team-tasks/issues/413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/190)

Cleanup renderer use in demos [skip ci]

---

demo/context-menu-basic-demos.html
src/vaadin-context-menu.html

Connected to https://github.com/vaadin/components-team-tasks/issues/416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/191)

Improve renderers docs [skip ci]

---

magi-p3-post.json
src/vaadin-contextmenu-items-mixin.html
test/items.html

Closes #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/207)

Close all menus on esc

---

src/vaadin-context-menu.html

Fixes https://github.com/vaadin/vaadin-context-menu/issues/210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/211)

docs: Add description of the item-selected event

---

src/vaadin-contextmenu-items-mixin.html
test/items.html
theme/lumo/vaadin-context-menu-styles.html
theme/material/vaadin-context-menu-styles.html

Fixes #212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/213)

Create extensions for context menu items

---

bower.json
demo/context-menu-grid-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/217)

Change 'Using with Vaadin Grid' demo to use vaadin-grid getEventContext API

---

src/vaadin-context-menu-overlay.html
src/vaadin-context-menu.html
src/vaadin-contextmenu-items-mixin.html
test/items.html

Fixes #218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/223)

fix: ensure consistent bottom alignment for nested menus

---

src/vaadin-contextmenu-items-mixin.html
test/items.html

fix #230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/233)

Fix: focus closed parent item when hover on non-parent

---

src/vaadin-contextmenu-items-mixin.html
test/items.html

Fix #231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/232)

Open sub-menu with enter and space keys

---

src/vaadin-context-menu.html
test/items.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/237)

Fix overlays position on scroll, add tests

---

src/vaadin-context-menu-overlay.html
src/vaadin-contextmenu-items-mixin.html
test/items.html

Fixes #240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/242)

fix: handle overlay up and down events properly

---

src/vaadin-context-menu.html
test/.eslintrc.json
test/common.js
test/integration.html
test/items.html
test/overlay.html

Fixes #153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-context-menu/243)

Fix context menu position on keyboard open

---

src/vaadin-contextmenu-event.html

Fixes https://github.com/vaadin/vaadin-context-menu-flow/issues/113
Related: https://github.com/vaadin/vaadin-grid/pull/1671

Fix ios detection for iOS 13 iPad

---

@types/interfaces.d.ts
bower.json
gen-tsd.json
magi-p3-post.js
package.json
src/vaadin-context-menu.html
src/vaadin-contextmenu-items-mixin.html

Fixes #271 
Generated TS definitions look like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {GestureEventListeners} from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';
import {FlattenedNodesObserver} from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';
import {ItemsMixin} from './vaadin-contextmenu-items-mixin.js';
import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';
import {ThemePropertyMixin} from '@vaadin/vaadin-themable-mixin/vaadin-theme-property-mixin.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
import {addListener, removeListener} from '@polymer/polymer/lib/utils/gestures.js';
declare class ContextMenuElement extends
ElementMixin(
ThemePropertyMixin(
ItemsMixin( …
```

feat: prepare for TS defs generation [skip ci]

---

@types/interfaces.d.ts

fix: make renderer params optional [skip ci]

---

src/vaadin-context-menu.html

Connected to vaadin/vaadin-core#257

docs: add JSDoc for attributes [skip ci]
